language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

matrix:
  fast_finish: true
    
before_script:
  # Set up Composer
  - composer self-update || true
  - composer install

script:
  - php ./vendor/bin/phpunit

after_script:
  - php ./vendor/bin/codacycoverage phpunit ../web/daric/coverage

after_success:
  - bash <(curl -s https://codecov.io/bash)
